CREATE SCHEMA IF NOT EXISTS project440;
USE project440;

CREATE USER IF NOT EXISTS 'pyconn'@'127.0.0.1' IDENTIFIED BY '1234';
CREATE USER IF NOT EXISTS 'pyconn'@'localhost' IDENTIFIED BY '1234';
GRANT SELECT, INSERT, UPDATE, CREATE ON project440.* TO 'pyconn'@'127.0.0.1';
GRANT SELECT, INSERT, UPDATE, CREATE ON project440.* TO 'pyconn'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS user (
  username VARCHAR(255) PRIMARY KEY,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(255) NOT NULL,
  CONSTRAINT u_email UNIQUE (email),
  CONSTRAINT u_phone UNIQUE (phone)
);
